# Docker Compose for Local Development! Not for general use

services:
  wavelog-ui:
    build: .
    # env_file:
    #   - .env
    ports:
      - "8088:80"
    volumes:
      - wavelog-config:/var/www/html/application/config/docker
      - wavelog-uploads:/var/www/html/uploads
      - wavelog-userdata:/var/www/html/userdata
    # command: ["./script.sh"]
    develop:
      watch:
        - action: sync+restart
          path: ./application/**/*
          target: /var/www/html/application/**/*

  wavelog-db:
    image: mariadb:11.3
    container_name: wavelog-db
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: yes
      MARIADB_DATABASE: wavelog
      MARIADB_USER: wavelog
      MARIADB_PASSWORD: wavelog # <- Insert a strong password here
    volumes:
      - wavelog-dbdata:/var/lib/mysql
    restart: unless-stopped

volumes:
  wavelog-dbdata:
  wavelog-uploads:
  wavelog-userdata:
  wavelog-config: