name: Issue Bot
on:
  workflow_dispatch:
  push:
    branches: dev
  schedule:
    - cron: "30 1 * * *"

jobs:
  close-issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/stale@v9.0.0
        with:
          any-of-labels: "wait 4 close"
          exempt-all-milestones: true
          exempt-issue-labels: "hold"
          days-before-issue-stale: 5
          days-before-issue-close: 3
          stale-issue-label: "stale"
          stale-issue-message: 'This issue is being automatically closed after 3 days.'
          close-issue-message: "This issue was closed because it has been inactive for 3 days since being marked as 'stale'."
          days-before-pr-stale: -1
          days-before-pr-close: -1
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          debug-only: true
